# Generated by Django 3.2.6 on 2021-09-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='cateogry',
            new_name='category',
        ),
    ]
