# Generated by Django 3.2.6 on 2021-08-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_delivery', models.IntegerField(choices=[('1', 'delivery'), ('0', 'eat_here')])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('status_order', models.IntegerField(choices=[('1', 'cooking'), ('2', 'delivery'), ('3', 'finish')], default='1')),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.salechannel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour_level', models.IntegerField(choices=[('0', 'non'), ('1', 'low'), ('2', 'midium'), ('3', 'much')])),
                ('flavour_type', models.IntegerField(choices=[('1', 'spicy'), ('2', 'sweet')])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desscriptions', models.TextField()),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.orderitem')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.topping')),
            ],
        ),
    ]
