# Generated by Django 3.0.7 on 2021-10-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pos_user',
            field=models.BooleanField(default=False),
        ),
    ]
