# Generated by Django 3.2.6 on 2021-08-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categort', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaleChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_channel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('1', 'able'), ('0', 'disable')], default='1')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_topping', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.salechannel')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('1', 'able'), ('0', 'disable')], default='1')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory')),
                ('type_topping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.typetopping')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.salechannel')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.topping')),
            ],
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.salechannel')),
            ],
        ),
    ]
