# Generated by Django 3.2.6 on 2021-09-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='categort',
            new_name='category',
        ),
    ]
